import type { BorrowerProfile, PersonaPreset } from "../types/credit";

export const DEFAULT_PROFILE: BorrowerProfile = {
  borrower_type: "gig_worker",
  monthly_inflow: 35000,
  upi_tx_count_monthly: 45,
  upi_debit_to_credit_ratio: 0.82,
  cashflow_volatility: 0.25,
  utility_payment_delay_days: 3,
  telecom_recharge_regularity: 0.95,
  gst_filing_punctuality: 0.0,
  ecommerce_cancellation_rate: 0.05,
  mobility_activity_score: 75.0,
  consent_artifact_id: null,
  data_source_mode: "MANUAL_SIMULATION",
};

export const PERSONA_PRESETS: PersonaPreset[] = [
  {
    id: "gig_prime",
    name: "Prime Gig Worker (Ravi K.)",
    shortName: "Prime Gig Worker",
    personName: "Ravi K.",
    description: "Consistent high-volume UPI transactions, low volatility, zero bill delay, high fleet mobility.",
    badge: "Prime Approved",
    dotColor: "emerald",
    phone: "+91-98765-43210",
    vpaHandle: "ravi.fleet@okhdfcbank",
    vehicleRc: "KA-01-EQ-4921",
    profile: {
      borrower_type: "gig_worker",
      monthly_inflow: 42000,
      upi_tx_count_monthly: 88,
      upi_debit_to_credit_ratio: 0.74,
      cashflow_volatility: 0.18,
      utility_payment_delay_days: 1,
      telecom_recharge_regularity: 0.98,
      gst_filing_punctuality: 0.0,
      ecommerce_cancellation_rate: 0.02,
      mobility_activity_score: 88.5,
      consent_artifact_id: null,
      data_source_mode: "MANUAL_SIMULATION",
    },
  },
  {
    id: "kirana_solid",
    name: "Solid Kirana Merchant (Gupta Stores)",
    shortName: "Solid Kirana Merchant",
    personName: "Gupta Stores",
    description: "High merchant turnover, robust GST compliance, disciplined utility payments, local logistics.",
    badge: "Solid Merchant",
    dotColor: "blue",
    phone: "+91-98111-22334",
    vpaHandle: "gupta.stores@oksbi",
    vehicleRc: "DL-1N-AA-9982",
    profile: {
      borrower_type: "kirana_merchant",
      monthly_inflow: 95000,
      upi_tx_count_monthly: 120,
      upi_debit_to_credit_ratio: 0.85,
      cashflow_volatility: 0.22,
      utility_payment_delay_days: 4,
      telecom_recharge_regularity: 0.92,
      gst_filing_punctuality: 0.88,
      ecommerce_cancellation_rate: 0.04,
      mobility_activity_score: 48.0,
      consent_artifact_id: null,
      data_source_mode: "MANUAL_SIMULATION",
    },
  },
  {
    id: "freelancer_review",
    name: "Borderline Freelancer (Ananya S.)",
    shortName: "Borderline Freelancer",
    personName: "Ananya S.",
    description: "High income spikes but moderate cashflow volatility. Borderline liquidity ratio, low mobility footprint.",
    badge: "Manual Review",
    dotColor: "amber",
    phone: "+91-99222-33445",
    vpaHandle: "ananya.design@okicici",
    vehicleRc: "MH-02-CR-1120",
    profile: {
      borrower_type: "freelancer",
      monthly_inflow: 68000,
      upi_tx_count_monthly: 28,
      upi_debit_to_credit_ratio: 0.96,
      cashflow_volatility: 0.48,
      utility_payment_delay_days: 12,
      telecom_recharge_regularity: 0.85,
      gst_filing_punctuality: 0.45,
      ecommerce_cancellation_rate: 0.08,
      mobility_activity_score: 34.0,
      consent_artifact_id: null,
      data_source_mode: "MANUAL_SIMULATION",
    },
  },
  {
    id: "delinquency_knockout",
    name: "Delinquency Knockout (Vikas M.)",
    shortName: "Delinquency Knockout",
    personName: "Vikas M.",
    description: "Breaches zero-tolerance policy with 28-day utility delay, extreme cashflow depletion, erratic mobility.",
    badge: "Hard Knockout",
    dotColor: "rose",
    phone: "+91-97333-44556",
    vpaHandle: "vikas.m@okaxis",
    vehicleRc: "DL-04-A-1002",
    profile: {
      borrower_type: "gig_worker",
      monthly_inflow: 22000,
      upi_tx_count_monthly: 14,
      upi_debit_to_credit_ratio: 1.15,
      cashflow_volatility: 0.86,
      utility_payment_delay_days: 28,
      telecom_recharge_regularity: 0.42,
      gst_filing_punctuality: 0.0,
      ecommerce_cancellation_rate: 0.28,
      mobility_activity_score: 12.0,
      consent_artifact_id: null,
      data_source_mode: "MANUAL_SIMULATION",
    },
  },
];
